# Generated by Django 5.0.3 on 2024-03-13 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Id', models.IntegerField()),
                ('Customer_Name', models.CharField(max_length=30)),
                ('Customer_Age', models.IntegerField()),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_Number', models.CharField(max_length=10)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instructor_Id', models.IntegerField()),
                ('Instructor_Name', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact_Number', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Physician_Id', models.IntegerField()),
                ('Physician_Name', models.CharField(max_length=30)),
                ('Physician_Email', models.EmailField(max_length=254)),
                ('Physician_Number', models.CharField(max_length=10)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
