# Generated by Django 5.0.3 on 2024-03-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_customer_instructor_physician'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('food_name', models.CharField(max_length=30)),
                ('food_details', models.TextField()),
            ],
        ),
    ]
