# Generated by Django 5.0.3 on 2024-03-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_diet'),
    ]

    operations = [
        migrations.AddField(
            model_name='diet',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
