# Generated by Django 5.0.3 on 2024-03-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0004_diet_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='image',
        ),
        migrations.AlterField(
            model_name='diet',
            name='food_image',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
