# Generated by Django 5.0.3 on 2024-03-30 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0008_customerdoubts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdoubts',
            name='user',
        ),
    ]
