# Generated by Django 5.0.3 on 2024-04-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0010_customercomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='FirstAid',
        ),
    ]
