# Generated by Django 5.0.3 on 2024-04-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0011_gymservices_delete_firstaid'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerComplaintAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now=True)),
                ('complaints', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
