# Generated by Django 5.0.3 on 2024-04-16 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0014_dietinst_delete_customercomplaintadmin_delete_diet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercomplaint',
            name='user5',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
