# Generated by Django 5.0.3 on 2024-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0016_customerdoubts_user4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=100)),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
