# Generated by Django 5.0.3 on 2024-04-23 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0017_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membershipjoinrequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(max_length=100)),
                ('membership_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.membership')),
            ],
        ),
        migrations.CreateModel(
            name='Membershipjoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.membershipjoinrequest')),
            ],
        ),
    ]
