# Generated by Django 5.0.3 on 2024-04-25 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0018_membershipjoinrequest_membershipjoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructorchoose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.instructor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
