# Generated by Django 5.0.3 on 2024-04-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0019_instructorchoose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Instructorchoose',
        ),
    ]
