# Generated by Django 5.0.3 on 2024-04-30 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0020_delete_instructorchoose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idietadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.TextField()),
                ('lunch', models.TextField()),
                ('dinner', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer')),
            ],
        ),
        migrations.DeleteModel(
            name='DietInst',
        ),
    ]
