# Generated by Django 5.0.3 on 2024-04-30 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0022_alter_idietadd_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idietadd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.customer'),
        ),
    ]
