# Generated by Django 5.0.3 on 2024-05-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0025_healthdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipjoin',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymapp.membership'),
        ),
        migrations.DeleteModel(
            name='Membershipjoinrequest',
        ),
    ]
