# Generated by Django 5.0.3 on 2024-05-18 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0027_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerFee',
        ),
    ]
