# Generated by Django 5.0.3 on 2024-05-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0028_delete_customerfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='fee_amount',
            field=models.CharField(max_length=100),
        ),
    ]
