# Generated by Django 5.0.3 on 2024-05-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0029_alter_fee_fee_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='name',
            new_name='customer_name',
        ),
    ]
