from django.urls import path

from gymapp import views

urlpatterns =[
     path("", views.index, name="index"),
     path("loginvw",views.loginview,name="loginvw"),
     path("dashboard", views.dashb, name="dash"),
     path("adminvw", views.adminRead, name="adminview"),
     path("instructorreg", views.InstructorRegister, name="instructor"),
     path("physicianreg", views.PhysicianRegister, name="physician"),
     path("instructorvw", views.InstructRead, name="instructorview"),
     path("physicianvw", views.PhysicianRead, name="physicianview"),
     path("customerreg", views.CustomerRegister, name="customer"),
     path("customervw", views.CustomerRead, name="customerview"),
     path("instructoradmin", views.Instruct_read, name="instructoradmin"),
     path("physicianadmin", views.Phy_read, name="physicianadmin"),
     path("customeradmin", views.Customer_read, name="customeradmin"),
     # path("equipments", views.Equipments, name="equipments"),
     # path("equipmentsview", views.Equipmentsview, name="equipmentsview"),

     # path("firstaidview", views.Firstaid, name="firstaidview"),
     path("custmember", views.CustomerMembership, name="customermember"),
     path("physiciancust", views.Phycustomerdetails, name="physiciancust"),
     path("custdoubts", views.Customerdoubts, name="custdoubts"),
     path("custdoubtsview", views.customerdoubtsview, name="custdoubtsview"),
     path("phydoubts", views.Customerdoubtsphy, name="phydoubts"),
     path("phydoubtsreply/<int:id>/", views.PhyReply, name="phydoubtsreply"),
     path("custcomplaints", views.Customercomplaints, name="custcomplaints"),
     path("custcomplaintsview", views.customercomplaintsview, name="custcomplaintsview"),
     path("custcomplaintsdelt/<int:id>/", views.Customercomplaintdelt, name="custcomplaintsdelt"),
     path("custgymservices", views.Custgymservices, name="custgymservices"),
     path("custgymservicesvw", views.Custgymservicesview, name="custgymservicesvw"),
     path("custgymservicedelt/<int:id>/",views.custgymservicesdelt,name="custgymservicedelt"),
     path("custgymservicedes/<int:id>/", views.Custgymservicedescription, name="custgymservicedes"),
     path("customergymvw", views.Customergymservicesview, name="customergymvw"),
     path("customergymdes/<int:id>/", views.Customergymservicedescription, name="customergymdes"),

     path("custcomplaintadmin", views.Customercomplaintadmin, name="custcomplaintadmin"),
     path("custcomplaintadmindelt/<int:id>/", views.Customercomplaintadmindelt, name="custcomplaintadmindelt"),
     path("replyadmin/<int:id>/", views.AdminReply, name="replyadmin"),
     path("customerfee", views.Customerfee, name="customerfee"),
     path("customerfeeview", views.CustomerFeeview, name="customerfeeview"),
     path("membership", views.MemberShip, name="membership"),
     path("membershipview", views.Membershipview, name="membershipview"),
     path("memberjoin/<int:id>/", views.MembershipJoin, name="memberjoin"),
     path("memberphy", views.MembershipPhy, name="memberphy"),
     path("memberapprove/<int:id>/", views.MembershipApprove, name="memberapprove"),
     path("memberreject/<int:id>/", views.Membershipreject, name="memberreject"),
     path("membershipadmin", views.MembershipAdminView, name="membershipadmin"),
     path("membershipdelt/<int:id>/", views.MembershipDelt, name="membershipdelt"),
     path("instdietadd", views.Instructor_dietadd, name="instdietadd"),
     path("instdietview", views.Instdietview, name="instdietview"),
     path("custdietview", views.Custdietview, name="custdietview"),
     path("instdietdelt/<int:id>/", views.Instdietdelt, name="instdietdelt"),
     path("instdietupdate/<int:id>/", views.Instdietupdate, name="instdietupdate"),
     path("healthdetails", views.CustHealthDetails, name="healthdetails"),
     path("healthdetailsview", views.CustHealthDetailsView, name="healthdetailsview"),
     path("healthdelt/<int:id>/", views.CustHealthDetailsDelt, name="healthdelt"),
     path("insthealthdetailsview", views.InstHealthDetailsView, name="insthealthdetailsview"),
     path("insthealthdelt/<int:id>/", views.InstHealthDetailsDelt, name="insthealthdelt"),
     path("logoutvw", views.Logoutview, name="logoutvw"),

]